name: Test

on: [push, pull_request]

jobs:
  build-cache:
    name: Build cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      name: Install Python 3.8
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Build cache
      run: |
        python -m pep600_compliance --cache-folder ./cache --readme ./README.rst --machine x86_64 i686 aarch64 ppc64le s390x armv7l
    - name: Create Pull Request
      if: github.event_name == 'push' && always()
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: auto-update cache and/or README.rst
        title: '[Bot] auto-update cache and/or README.rst'
