name: Test

on:
  push:
    paths: 'pep600_compliance/**'
  pull_request:
    paths: 'pep600_compliance/**'

jobs:
  build-cache:
    name: Build cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      name: Install Python 3.8
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Build cache
      run: |
        python -m pep600_compliance --cache-folder ./cache --readme ./README.rst --machine x86_64
