name: Cron Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build-cache:
    name: Build cache
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Install Python 3.8
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        docker pull multiarch/qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Build cache
      run: |
        python -m pep600_compliance --force-rolling --machine x86_64
        if ! git diff --exit-code --quiet cache; then
          python -m pep600_compliance --force-rolling --machine i686 aarch64 ppc64le s390x armv7l
        fi
    - name: Create Pull Request
      if: github.ref == 'refs/heads/master' && always()
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: auto-update cache and/or README.rst
        title: '[Bot] auto-update cache and/or README.rst'
